INGREDIENTS_SEED = [
  {"strIngredient1":"Light rum", "category":"liquor"},
  {"strIngredient1":"Gin", "category":"liquor"},
  {"strIngredient1":"Dark rum", "category":"liquor"},
  {"strIngredient1":"Sweet Vermouth", "category":"liquor"},
  {"strIngredient1":"Strawberry schnapps", "category":"liquor"},
  {"strIngredient1":"Scotch", "category":"liquor"},
  {"strIngredient1":"Apricot brandy", "category":"liquor"},
  {"strIngredient1":"Triple sec", "category":"liquor"},
  {"strIngredient1":"Southern Comfort", "category":"liquor"},
  {"strIngredient1":"Orange bitters", "category":"others"},
  {"strIngredient1":"Brandy", "category":"liquor"},
  {"strIngredient1":"Lemon vodka", "category":"liquor"},
  {"strIngredient1":"Blended whiskey", "category":"liquor"},
  {"strIngredient1":"Dry Vermouth", "category":"liquor"},
  {"strIngredient1":"Amaretto", "category":"liquor"},
  {"strIngredient1":"Tea", "category":"non-alcohol drink"},
  {"strIngredient1":"Champagne", "category":"liquor"},
  {"strIngredient1":"Bourbon", "category":"liquor"},
  {"strIngredient1":"Tequila", "category":"liquor"},
  {"strIngredient1":"Vodka", "category":"liquor"},
  {"strIngredient1":"Bitters", "category":"others"},
  {"strIngredient1":"Sugar", "category":"others"},
  {"strIngredient1":"Kahlua", "category":"liquor"},
  {"strIngredient1":"Dubonnet Rouge", "category":"liquor"},
  {"strIngredient1":"Lime juice", "category":"fruit-juice"},
  {"strIngredient1":"Irish whiskey", "category":"liquor"},
  {"strIngredient1":"Apple brandy", "category":"liquor"},
  {"strIngredient1":"Carbonated water", "category":"non-alcohol drink"},
  {"strIngredient1":"Cherry brandy", "category":"liquor"},
  {"strIngredient1":"Creme de Cacao", "category":"liquor"},
  {"strIngredient1":"Grenadine", "category":"others"},
  {"strIngredient1":"Coffee brandy", "category":"liquor"},
  {"strIngredient1":"Red wine", "category":"liquor"},
  {"strIngredient1":"Rum", "category":"liquor"},
  {"strIngredient1":"Grapefruit juice", "category":"fruit-juice"},
  {"strIngredient1":"Ricard", "category":"liquor"},
  {"strIngredient1":"Sherry", "category":"liquor"},
  {"strIngredient1":"Cognac", "category":"liquor"},
  {"strIngredient1":"Sloe gin", "category":"liquor"},
  {"strIngredient1":"Apple juice", "category":"fruit-juice"},
  {"strIngredient1":"Pineapple juice", "category":"fruit-juice"},
  {"strIngredient1":"Lemon juice", "category":"fruit-juice"},
  {"strIngredient1":"Sugar syrup", "category":"others"},
  {"strIngredient1":"Milk", "category":"non-alcohol drink"},
  {"strIngredient1":"Strawberries", "category":"fruit-juice"},
  {"strIngredient1":"Chocolate syrup", "category":"others"},
  {"strIngredient1":"Yoghurt", "category":"others"},
  {"strIngredient1":"Mango", "category":"fruit-juice"},
  {"strIngredient1":"Ginger", "category":"others"},
  {"strIngredient1":"Grapes", "category":"fruit-juice"},
  {"strIngredient1":"Kiwi", "category":"fruit-juice"},
  {"strIngredient1":"Tomato juice", "category":"non-alcohol drink"},
  {"strIngredient1":"Cocoa powder", "category":"others"},
  {"strIngredient1":"Chocolate", "category":"others"},
  {"strIngredient1":"Heavy cream", "category":"others"},
  {"strIngredient1":"Galliano", "category":"liquor"},
  {"strIngredient1":"Peach Vodka", "category":"liquor"},
  {"strIngredient1":"Ouzo", "category":"liquor"},
  {"strIngredient1":"Coffee", "category":"non-alcohol drink"},
  {"strIngredient1":"Water", "category":"non-alcohol drink"},
  {"strIngredient1":"Espresso", "category":"non-alcohol drink"},
  {"strIngredient1":"Angelica root", "category":"others"},
  {"strIngredient1":"Orange", "category":"fruit-juice"},
  {"strIngredient1":"Cranberries", "category":"fruit-juice"},
  {"strIngredient1":"Apple cider", "category":"non-alcohol drink"},
  {"strIngredient1":"Everclear", "category":"liquor"},
  {"strIngredient1":"Cranberry juice", "category":"fruit-juice"},
  {"strIngredient1":"Egg yolk", "category":"non-alcohol drink"},
  {"strIngredient1":"Egg", "category":"others"},
  {"strIngredient1":"Lemon", "category":"fruit-juice"},
  {"strIngredient1":"Firewater", "category":"non-alcohol drink"},
  {"strIngredient1":"Lemonade", "category":"non-alcohol drink"},
  {"strIngredient1":"Whiskey", "category":"liquor"},
  {"strIngredient1":"Midori melon liqueur", "category":"liquor"},
  {"strIngredient1":"Sambuca", "category":"liquor"},
  {"strIngredient1":"Blackberry brandy", "category":"liquor"},
  {"strIngredient1":"Peppermint schnapps", "category":"liquor"},
  {"strIngredient1":"Creme de Cassis", "category":"liquor"},
  {"strIngredient1":"Cointreau", "category":"liquor"},
  {"strIngredient1":"Vermouth", "category":"liquor"},
  {"strIngredient1":"Advocaat", "category":"liquor"},
  {"strIngredient1":"Beer", "category":"liquor"},
  {"strIngredient1":"White Creme de Menthe", "category":"liquor"},
  {"strIngredient1":"Malibu rum", "category":"liquor"},
  {"strIngredient1":"Vanilla vodka", "category":"liquor"},
  {"strIngredient1":"Kiwi liqueur", "category":"liquor"},
  {"strIngredient1":"Cachaca", "category":"liquor"},
  {"strIngredient1":"Peachtree schnapps", "category":"liquor"},
  {"strIngredient1":"Cranberry vodka", "category":"liquor"},
  {"strIngredient1":"Orange juice", "category":"fruit-juice"},
  {"strIngredient1":"Chocolate ice-cream", "category":"others"},
  {"strIngredient1":"Banana liqueur", "category":"liquor"},
  {"strIngredient1":"Black Sambuca", "category":"liquor"},
  {"strIngredient1":"Mint", "category":"others"},
  {"strIngredient1":"Campari", "category":"liquor"},
  {"strIngredient1":"Sour mix", "category":"others"},
  {"strIngredient1":"Absinthe", "category":"liquor"},
  {"strIngredient1":"Vanilla ice-cream", "category":"others"},
  {"strIngredient1":"Chambord raspberry liqueur", "category":"liquor"},
  {"strIngredient1":"Fruit punch", "category":"others"},
  {"strIngredient1":"Blue Curacao", "category":"liquor"},
  {"strIngredient1":"Cola", "category":"non-alcohol drink"},
  {"strIngredient1":"Raspberry vodka", "category":"liquor"},
  {"strIngredient1":"Green Creme de Menthe", "category":"liquor"},
  {"strIngredient1":"Lemon peel", "category":"others"},
  {"strIngredient1":"Mezcal", "category":"liquor"},
  {"strIngredient1":"Green Chartreuse", "category":"liquor"},
  {"strIngredient1":"Hot Chocolate", "category":"others"},
]
