INGREDIENTS_SEED = [
  {"name":"Light rum", "category":"liquor"},
  {"name":"Gin", "category":"liquor"},
  {"name":"Dark rum", "category":"liquor"},
  {"name":"Sweet Vermouth", "category":"liquor"},
  {"name":"Strawberry schnapps", "category":"liquor"},
  {"name":"Scotch", "category":"liquor"},
  {"name":"Apricot brandy", "category":"liquor"},
  {"name":"Triple sec", "category":"liquor"},
  {"name":"Southern Comfort", "category":"liquor"},
  {"name":"Orange bitters", "category":"others"},
  {"name":"Brandy", "category":"liquor"},
  {"name":"Lemon vodka", "category":"liquor"},
  {"name":"Blended whiskey", "category":"liquor"},
  {"name":"Dry Vermouth", "category":"liquor"},
  {"name":"Amaretto", "category":"liquor"},
  {"name":"Tea", "category":"non-alcohol drink"},
  {"name":"Champagne", "category":"liquor"},
  {"name":"Bourbon", "category":"liquor"},
  {"name":"Tequila", "category":"liquor"},
  {"name":"Vodka", "category":"liquor"},
  {"name":"Bitters", "category":"others"},
  {"name":"Sugar", "category":"others"},
  {"name":"Kahlua", "category":"liquor"},
  {"name":"Dubonnet Rouge", "category":"liquor"},
  {"name":"Lime juice", "category":"fruit-juice"},
  {"name":"Irish whiskey", "category":"liquor"},
  {"name":"Apple brandy", "category":"liquor"},
  {"name":"Carbonated water", "category":"non-alcohol drink"},
  {"name":"Cherry brandy", "category":"liquor"},
  {"name":"Creme de Cacao", "category":"liquor"},
  {"name":"Grenadine", "category":"others"},
  {"name":"Coffee brandy", "category":"liquor"},
  {"name":"Red wine", "category":"liquor"},
  {"name":"Rum", "category":"liquor"},
  {"name":"Grapefruit juice", "category":"fruit-juice"},
  {"name":"Ricard", "category":"liquor"},
  {"name":"Sherry", "category":"liquor"},
  {"name":"Cognac", "category":"liquor"},
  {"name":"Sloe gin", "category":"liquor"},
  {"name":"Apple juice", "category":"fruit-juice"},
  {"name":"Pineapple juice", "category":"fruit-juice"},
  {"name":"Lemon juice", "category":"fruit-juice"},
  {"name":"Sugar syrup", "category":"others"},
  {"name":"Milk", "category":"non-alcohol drink"},
  {"name":"Strawberries", "category":"fruit-juice"},
  {"name":"Chocolate syrup", "category":"others"},
  {"name":"Yoghurt", "category":"others"},
  {"name":"Mango", "category":"fruit-juice"},
  {"name":"Ginger", "category":"others"},
  {"name":"Grapes", "category":"fruit-juice"},
  {"name":"Kiwi", "category":"fruit-juice"},
  {"name":"Tomato juice", "category":"non-alcohol drink"},
  {"name":"Cocoa powder", "category":"others"},
  {"name":"Chocolate", "category":"others"},
  {"name":"Heavy cream", "category":"others"},
  {"name":"Galliano", "category":"liquor"},
  {"name":"Peach Vodka", "category":"liquor"},
  {"name":"Ouzo", "category":"liquor"},
  {"name":"Coffee", "category":"non-alcohol drink"},
  {"name":"Water", "category":"non-alcohol drink"},
  {"name":"Espresso", "category":"non-alcohol drink"},
  {"name":"Angelica root", "category":"others"},
  {"name":"Orange", "category":"fruit-juice"},
  {"name":"Cranberries", "category":"fruit-juice"},
  {"name":"Apple cider", "category":"non-alcohol drink"},
  {"name":"Everclear", "category":"liquor"},
  {"name":"Cranberry juice", "category":"fruit-juice"},
  {"name":"Egg yolk", "category":"non-alcohol drink"},
  {"name":"Egg", "category":"others"},
  {"name":"Lemon", "category":"fruit-juice"},
  {"name":"Firewater", "category":"non-alcohol drink"},
  {"name":"Lemonade", "category":"non-alcohol drink"},
  {"name":"Whiskey", "category":"liquor"},
  {"name":"Midori melon liqueur", "category":"liquor"},
  {"name":"Sambuca", "category":"liquor"},
  {"name":"Blackberry brandy", "category":"liquor"},
  {"name":"Peppermint schnapps", "category":"liquor"},
  {"name":"Creme de Cassis", "category":"liquor"},
  {"name":"Cointreau", "category":"liquor"},
  {"name":"Vermouth", "category":"liquor"},
  {"name":"Advocaat", "category":"liquor"},
  {"name":"Beer", "category":"liquor"},
  {"name":"White Creme de Menthe", "category":"liquor"},
  {"name":"Malibu rum", "category":"liquor"},
  {"name":"Vanilla vodka", "category":"liquor"},
  {"name":"Kiwi liqueur", "category":"liquor"},
  {"name":"Cachaca", "category":"liquor"},
  {"name":"Peachtree schnapps", "category":"liquor"},
  {"name":"Cranberry vodka", "category":"liquor"},
  {"name":"Orange juice", "category":"fruit-juice"},
  {"name":"Chocolate ice-cream", "category":"others"},
  {"name":"Banana liqueur", "category":"liquor"},
  {"name":"Black Sambuca", "category":"liquor"},
  {"name":"Mint", "category":"others"},
  {"name":"Campari", "category":"liquor"},
  {"name":"Sour mix", "category":"others"},
  {"name":"Absinthe", "category":"liquor"},
  {"name":"Vanilla ice-cream", "category":"others"},
  {"name":"Chambord raspberry liqueur", "category":"liquor"},
  {"name":"Fruit punch", "category":"others"},
  {"name":"Blue Curacao", "category":"liquor"},
  {"name":"Cola", "category":"non-alcohol drink"},
  {"name":"Raspberry vodka", "category":"liquor"},
  {"name":"Green Creme de Menthe", "category":"liquor"},
  {"name":"Lemon peel", "category":"others"},
  {"name":"Mezcal", "category":"liquor"},
  {"name":"Green Chartreuse", "category":"liquor"},
  {"name":"Hot Chocolate", "category":"others"},
]
